on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: npm test
      - uses: davelosert/vitest-coverage-report-action@v2
        if: always()

  xo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        with:
          install-options: --ignore-scripts
      - run: npm run xo
